name: redeploy main app

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Trigger DO rebuild
        run: doctl apps create-deployment ${{ secrets.APP_ID }} --force-rebuild
